/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragonrental.gui;


import dragonrental.backend.*;
import dragonrental.common.IllegalEntityException;
import dragonrental.common.ServiceFailureException;
import dragonrental.common.ValidationException;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
        
/**
 *
 * @author zuz
 */
public class FilterPersonDialog extends javax.swing.JDialog {

    private PersonManager manager;
    private PeopleTableModel model;
    private final ResourceBundle bundle = ResourceBundle.getBundle("dragonrental/gui/language");
    
    /**
     * Creates new form FilterPersonDialog
     */
    public FilterPersonDialog(java.awt.Frame parent, boolean modal, PersonManager manager, PeopleTableModel model) {
        super(parent, modal);
        initComponents();
        this.manager = manager;
        this.model = model;
        setLocationRelativeTo(parent);
        setVisible(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        getNameField = new javax.swing.JTextField();
        getSurnameField = new javax.swing.JTextField();
        getEmailField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        filterPeopleButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("dragonrental/gui/language"); // NOI18N
        setTitle(bundle.getString("filter")); // NOI18N

        jLabel2.setText(bundle.getString("name:")); // NOI18N

        jLabel3.setText(bundle.getString("surname:")); // NOI18N

        jLabel4.setText(bundle.getString("email:")); // NOI18N

        getNameField.setToolTipText(bundle.getString("name")); // NOI18N

        getSurnameField.setToolTipText(bundle.getString("surname")); // NOI18N

        getEmailField.setToolTipText(bundle.getString("email")); // NOI18N

        backButton.setText(bundle.getString("back")); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        filterPeopleButton.setText(bundle.getString("filter")); // NOI18N
        filterPeopleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterPeopleButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filterPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getNameField)
                            .addComponent(getEmailField)
                            .addComponent(getSurnameField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(getNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(getSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(getEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(filterPeopleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void filterPeopleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterPeopleButtonMouseClicked
        Person per = new Person();
        String name = getNameField.getText();
        String surname = getSurnameField.getText();
        String email = getEmailField.getText();
        if(name.isEmpty()) {
            name = null;
        }
        if(surname.isEmpty()) {
            surname = null;
        }
        if(email.isEmpty()) {
            email = null;
        }
        per.setEmail(email);
        per.setSurname(surname);
        per.setName(name);
        per.setId(null);
  
        new FilterPeopleWorker(per, this).execute();
    }//GEN-LAST:event_filterPeopleButtonMouseClicked

    private class FilterPeopleWorker extends SwingWorker<Void,Void> {
        private Person person;
        private javax.swing.JDialog parent;
        private List<Person> people; 
        
        public FilterPeopleWorker(Person person, javax.swing.JDialog parent) {
            this.person = person;
            this.parent = parent;
            this.people = null;
        }
        
        @Override
        protected Void doInBackground() {
            try {
                this.people = manager.findPeople(person);
            } 
            catch(ServiceFailureException | ValidationException | IllegalEntityException | IllegalStateException | IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(parent,
                ex.getMessage(),
                bundle.getString("error"),
                JOptionPane.ERROR_MESSAGE);
            }
            return null;
        }
        
        @Override
        protected void done(){
            model.setPeople(this.people);
            model.fireTableDataChanged();
            parent.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton filterPeopleButton;
    private javax.swing.JTextField getEmailField;
    private javax.swing.JTextField getNameField;
    private javax.swing.JTextField getSurnameField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
