/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragonrental.gui;

import dragonrental.backend.Dragon;
import dragonrental.backend.DragonElement;
import dragonrental.backend.DragonManager;
import dragonrental.common.IllegalEntityException;
import dragonrental.common.ServiceFailureException;
import dragonrental.common.ValidationException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author zuz
 */
public class FilterDragonDialog extends javax.swing.JDialog {

    private DragonManager manager;
    private DragonTableModel model;
    private ResourceBundle bundle = ResourceBundle.getBundle("dragonrental/gui/language");
    
    /**
     * Creates new form FilterDragonDialog
     */
    public FilterDragonDialog(java.awt.Frame parent, boolean modal, DragonManager manager, DragonTableModel model) {
        super(parent, modal);
        this.manager = manager;
        this.model = model;
        initComponents();
        setLocationRelativeTo(parent);
        setVisible(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        speedSpinner = new javax.swing.JSpinner();
        elementComboBox = new javax.swing.JComboBox<>();
        speedCheckBox = new javax.swing.JCheckBox();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("dragonrental/gui/language"); // NOI18N
        setTitle(bundle.getString("filterDragons")); // NOI18N

        jLabel1.setText(bundle.getString("dragonName:")); // NOI18N

        jLabel2.setText(bundle.getString("birth_date:")); // NOI18N

        jLabel3.setText(bundle.getString("element:")); // NOI18N

        jLabel5.setText(bundle.getString("speed:")); // NOI18N

        nameField.setToolTipText(bundle.getString("name")); // NOI18N

        filterButton.setText(bundle.getString("filter")); // NOI18N
        filterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterButtonMouseClicked(evt);
            }
        });

        cancelButton.setText(bundle.getString("cancel")); // NOI18N
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        elementComboBox.setModel(new DefaultComboBoxModel(DragonElement.values()));

        speedCheckBox.setText(bundle.getString("speed_independent")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(elementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedCheckBox)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(elementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(speedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speedCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        elementComboBox.insertItemAt("",0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterButtonMouseClicked
        Dragon dragonFilter = new Dragon();
        
        String name = nameField.getText();
        if (name.isEmpty()) {
            name = null;
        }
        
        String dragonElement = elementComboBox.getSelectedItem().toString();
        DragonElement element = null;
        if (!dragonElement.isEmpty()) {
            element = (DragonElement)elementComboBox.getSelectedItem();
        }
        
        Integer speed = null;
        if (!speedCheckBox.isSelected()) {
            speed = (Integer) speedSpinner.getValue();
        }
        
        LocalDate birthDate = null;
        if (jXDatePicker1.getDate() != null) {
            try {
                birthDate = LocalDate.parse(jXDatePicker1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate().toString());
            } catch (DateTimeParseException ex) {
                JOptionPane.showMessageDialog(this,
                        bundle.getString("date_parse_error"),
                        bundle.getString("error"),
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        dragonFilter.setName(name);
        dragonFilter.setElement(element);
        dragonFilter.setDateOfBirth(birthDate);
        dragonFilter.setMaximumSpeed(speed);
        
        new FilterDragonWorker(dragonFilter,this).execute();
    }//GEN-LAST:event_filterButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    private class FilterDragonWorker extends SwingWorker<Void, Void> {
        private Dragon dragon;
        private javax.swing.JDialog parent;
        private List<Dragon> dragons;
        
        public FilterDragonWorker(Dragon dragon, javax.swing.JDialog parent) {
            this.dragon = dragon;
            this.parent = parent;
        }
        
        @Override
        protected Void doInBackground() {
            try {
                this.dragons = manager.findDragons(dragon);
            } 
            catch(ServiceFailureException | ValidationException | IllegalEntityException | IllegalStateException | IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(parent,
                ex.getMessage(),
                bundle.getString("error"),
                JOptionPane.ERROR_MESSAGE);
            }
            return null;
        }
        
        @Override
        protected void done(){
            model.setDragons(this.dragons);
            model.fireTableDataChanged();
            parent.dispose();
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> elementComboBox;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField nameField;
    private javax.swing.JCheckBox speedCheckBox;
    private javax.swing.JSpinner speedSpinner;
    // End of variables declaration//GEN-END:variables
}
