/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragonrental.gui;

import dragonrental.backend.*;
import dragonrental.common.*;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Blackfox
 */
public class PayReservationDialog extends UpdateReservation {

    private ReservationManager reservationManager;
    private ResourceBundle bundle = ResourceBundle.getBundle("dragonrental/gui/language");
    private Reservation reservation;
    
    /**
     * Creates new form PayReservationDialog
     */
    public PayReservationDialog(java.awt.Frame parent, boolean modal, ReservationManager manager, int row, ReservationsTableModel model) {
        super(parent, modal, manager, row, model);
        
        this.reservationManager = manager;
        this.reservation = model.getElementAt(row);
        
        initComponents();
        setLocationRelativeTo(parent);
        setVisible(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        borrowerLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dragonLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pricePerHourLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        moneyPaidLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("dragonrental/gui/language"); // NOI18N
        jLabel1.setText(bundle.getString("payReservation")); // NOI18N

        jLabel2.setText(bundle.getString("borrower")); // NOI18N

        borrowerLabel.setText(reservation.getBorrower().getName()+' '+reservation.getBorrower().getSurname());

        jLabel4.setText(bundle.getString("dragon")); // NOI18N

        dragonLabel.setText(reservation.getDragon().getName());

        jLabel6.setText(bundle.getString("from")); // NOI18N

        fromLabel.setText(reservation.getFrom().format(DateTimeFormatter.ofLocalizedDateTime(GUIUtils.getDateTimeFormat())));

        jLabel8.setText(bundle.getString("to")); // NOI18N

        toLabel.setText(reservation.getTo() == null ? bundle.getString("noEnd") : reservation.getTo().format(DateTimeFormatter.ofLocalizedDateTime(GUIUtils.getDateTimeFormat())));

        jLabel10.setText(bundle.getString("pricePerHour")); // NOI18N

        pricePerHourLabel.setText(reservation.getPricePerHour().toString());

        jLabel12.setText(bundle.getString("moneyPaid")); // NOI18N

        moneyPaidLabel.setText(reservation.getMoneyPaid().toString());

        jLabel14.setText(bundle.getString("pay")); // NOI18N

        amountTextField.setToolTipText(bundle.getString("amount")); // NOI18N

        cancelButton.setText(bundle.getString("cancel")); // NOI18N
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        payButton.setText(bundle.getString("pay")); // NOI18N
        payButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payButtonMouseClicked(evt);
            }
        });

        jLabel3.setText(bundle.getString("totalPrice")); // NOI18N

        jLabel5.setText(GUIUtils.getDuePayment(reservation).toString()
        );

        jLabel7.setText(bundle.getString("reservationStatus")); // NOI18N

        jLabel9.setText(GUIUtils.getReservationStatusString(reservation)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(payButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moneyPaidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addGap(0, 29, Short.MAX_VALUE))
                            .addComponent(pricePerHourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fromLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dragonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrowerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(amountTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(borrowerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dragonLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fromLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(toLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pricePerHourLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(moneyPaidLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(payButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payButtonMouseClicked
        Reservation newReservation = reservationManager.getReservation(reservation.getId());
        try {
            newReservation.setMoneyPaid( reservation.getMoneyPaid().add(new BigDecimal(amountTextField.getText())) );
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                bundle.getString("wrongNumberFormat"),
                bundle.getString("updateReservationError"),
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        String error = Validation.validateReservationForUpdating(reservation, newReservation);
        
        if(error != null) {
            JOptionPane.showMessageDialog(this,
                bundle.getString(error),
                bundle.getString("updateReservationError"),
                JOptionPane.WARNING_MESSAGE);
        }
        else {
            new UpdateReservationWorker(newReservation, this).execute();
        }
    }//GEN-LAST:event_payButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel borrowerLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dragonLabel;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel moneyPaidLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel pricePerHourLabel;
    private javax.swing.JLabel toLabel;
    // End of variables declaration//GEN-END:variables

    
}
