/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dragonrental.gui;

import dragonrental.backend.*;
import dragonrental.common.IllegalEntityException;
import dragonrental.common.ServiceFailureException;
import dragonrental.common.Validation;
import dragonrental.common.ValidationException;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author zuz
 */
public class UpdatePersonDialog extends javax.swing.JDialog {

    private PersonManager manager;
    private Person person;
    private PeopleTableModel model;
    private int row;
    private ResourceBundle bundle = ResourceBundle.getBundle("dragonrental/gui/language");
    
    /**
     * Creates new form UpdatePersonDialog
     */
    public UpdatePersonDialog(java.awt.Frame parent, boolean modal, PersonManager manager, int selectedRow, PeopleTableModel model) {
        super(parent, modal);
        this.manager = manager;
        this.model = model;
        this.person = (Person) model.getElementAt(selectedRow);
        this.row = selectedRow;
        initComponents();
        setLocationRelativeTo(parent);
        setVisible(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        getSurnameField = new javax.swing.JTextField();
        getEmailField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        getNameField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("dragonrental/gui/language"); // NOI18N
        setTitle(bundle.getString("updatePerson")); // NOI18N

        jLabel3.setText(bundle.getString("email:")); // NOI18N

        getSurnameField.setText(person.getSurname());

        getEmailField.setText(person.getEmail());

        jButton2.setText(bundle.getString("back")); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel2.setText(bundle.getString("surname:")); // NOI18N

        jLabel4.setText(bundle.getString("name:")); // NOI18N

        getNameField.setText(person.getName());

        jButton3.setText(bundle.getString("update")); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(getSurnameField)
                            .addComponent(getEmailField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(getNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(getSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(getEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Person per = new Person();
        per.setEmail(getEmailField.getText());
        per.setSurname(getSurnameField.getText());
        per.setName(getNameField.getText());
        per.setId(this.person.getId());
        
        String error = Validation.personValidator(per);
        
        if(error != null) {
            JOptionPane.showMessageDialog(this,
                bundle.getString(error),
                bundle.getString("addPersonError"),
                JOptionPane.WARNING_MESSAGE);
        }
        else {
            new UpdatePersonWorker(per, this).execute();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private class UpdatePersonWorker extends SwingWorker<Void,Void> {
        private Person person;
        private javax.swing.JDialog parent;
        private int error;
        
        public UpdatePersonWorker(Person person, javax.swing.JDialog parent) {
            this.person = person;
            this.parent = parent;
            this.error = 0;
        }
        
        @Override
        protected Void doInBackground() {
            try {
                manager.updatePerson(person);
            } 
            catch(ServiceFailureException | ValidationException | IllegalEntityException | IllegalStateException ex) {
                JOptionPane.showMessageDialog(parent,
                ex.getMessage(),
                bundle.getString("addPersonError"),
                JOptionPane.ERROR_MESSAGE);
                this.error = 1;
                return null;
            }
            JOptionPane.showMessageDialog(parent,
                bundle.getString("done"),
                bundle.getString("addPerson"),
                JOptionPane.INFORMATION_MESSAGE);
            return null;
        }
        
        @Override
        protected void done(){
            if(error == 0) {
                model.setElementAt(row, person);
                model.fireTableRowsUpdated(row, row);
                parent.dispose();
            }
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField getEmailField;
    private javax.swing.JTextField getNameField;
    private javax.swing.JTextField getSurnameField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
